image: node:latest

pages:
  stage: deploy
  script:
    - npm config set registry https://registry.npmjs.org/
    - npm i
    - npm run build
    - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master